Catch NoClassDefFoundError exceptions where necessary
Prevent crashes when publishers import MoPub's SDK via modules and when the app does not have all of them.